# Exploratory Data Analysis

## Outline

- Random Variable: A phenomenon whose outcome is not yet known
- Statistics, Machine Learning: Guessing future values of a phenomenon, based on past observations
- Exploratory Data Analysis: Discovering basic features of variables

1. Analyze categorical/numeric variables: Mean/standard deviation, median/IQR, 
2. Analyze pairs of categorical/numeric variables

# 1. Single Variables

## Recall: Getting to Know a Variable
- Current data type, `df[var].dtype`
- Number of missings, `df[var].isna().sum()`
- Unique values it takes, `df[var].unique()`
- Counts associated with unique values, `df[var].value_counts()`
- Histogram of the value counts, `df[var].hist( bins = 35 )`

> From this, you should be able to decide whether the variable is clean enough to proceed; otherwise, go back and clean it again

In [9]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
import plotly.express as px

df = pd.read_csv('airbnb_hw.csv',low_memory=False)
df.head()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [ ]:
df.dtypes

# possible probelms: we have a lot of objects, we also maybe want the zipcodes to be floars

Host Id                         int64
Host Since                     object
Name                           object
Neighbourhood                  object
Property Type                  object
Review Scores Rating (bin)    float64
Room Type                      object
Zipcode                       float64
Beds                          float64
Number of Records               int64
Number Of Reviews               int64
Price                          object
Review Scores Rating          float64
dtype: object

In [17]:
pd.to_numeric(df["Price"].str.replace(",","").str.replace("$",""))

0        145
1         37
2         28
3        199
4        549
        ...
30473    300
30474    125
30475     80
30476     35
30477     80
Name: Price, Length: 30478, dtype: int64

In [ ]:
df.info # gives us the data type and its still an object for price

<bound method DataFrame.info of         Host Id Host Since                                Name Neighbourhood   \
0       5162530        NaN     1 Bedroom in Prime Williamsburg       Brooklyn
1      33134899        NaN     Sunny, Private room in Bushwick       Brooklyn
2      39608626        NaN                Sunny Room in Harlem      Manhattan
3           500  6/26/2008  Gorgeous 1 BR with Private Balcony      Manhattan
4           500  6/26/2008            Trendy Times Square Loft      Manhattan
...         ...        ...                                 ...            ...
30473  43022976  8/31/2015   10 Mins to Time Square/two floors         Queens
30474  42993382  8/31/2015       1BR ocean view & F,Q train st       Brooklyn
30475  43033067  8/31/2015                Amazing Private Room       Brooklyn
30476  43000991  8/31/2015   Charming private female room: UWS      Manhattan
30477  42999189  8/31/2015    Huge Beautiful Bedroom - Astoria         Queens

      Property Type  Review Scores Rating (bin)        Room Type  Zipcode  \
0         Apartment                         NaN  Entire home/apt  11249.0
1         Apartment                         NaN     Private room  11206.0
2         Apartment                         NaN     Private room  10032.0
3         Apartment                         NaN  Entire home/apt  10024.0
4         Apartment                        95.0     Private room  10036.0
...             ...                         ...              ...      ...
30473     Apartment                         NaN  Entire home/apt  11101.0
30474     Apartment                         NaN     Private room  11224.0
30475         Other                         NaN     Private room  11206.0
30476     Apartment                         NaN     Private room  10025.0
30477         House                         NaN     Private room  11105.0

       Beds  Number of Records  Number Of Reviews Price  Review Scores Rating
0       1.0                  1                  0   145                   NaN
1       1.0                  1                  1    37                   NaN
2       1.0                  1                  1    28                   NaN
3       3.0                  1                  0   199                   NaN
4       3.0                  1                 39   549                  96.0
...     ...                ...                ...   ...                   ...
30473   5.0                  1                  0   300                   NaN
30474   2.0                  1                  0   125                   NaN
30475   1.0                  1                  0    80                   NaN
30476   1.0                  1                  0    35                   NaN
30477   1.0                  1                  0    80                   NaN

[30478 rows x 13 columns]>

In [ ]:
df["Price"] = pd.to_numeric(df["Price"].str.replace(",","").str.replace("$",""))

df.info # idfk

AttributeError: Can only use .str accessor with string values!

Property Type
Apartment          27102
House               2090
Loft                 753
Bed & Breakfast      180
Townhouse            136
Condominium           94
Other                 47
Dorm                  31
Boat                   8
Villa                  8
Camper/RV              7
Bungalow               4
Treehouse              4
Tent                   4
Hut                    2
Cabin                  2
Lighthouse             1
Chalet                 1
Castle                 1
Name: count, dtype: int64

## Statistics
- A **statistic** is a function that maps data into a number
    - Proportion: What proportion of observations take a particular label?
    - Mean: What is the average of the recorded values of the variable?

In [24]:
df['Property Type'].value_counts()

Property Type
Apartment          27102
House               2090
Loft                 753
Bed & Breakfast      180
Townhouse            136
Condominium           94
Other                 47
Dorm                  31
Boat                   8
Villa                  8
Camper/RV              7
Bungalow               4
Treehouse              4
Tent                   4
Hut                    2
Cabin                  2
Lighthouse             1
Chalet                 1
Castle                 1
Name: count, dtype: int64

### What is a statisic?

f(data -> #)
plug in data, get a number, can get statistics about statistics

### Random data? 
we have a data frame, our rows are observations. our columns are vairables 

a random variable maps an observation to a valriable 

f(obs -> $\mathbb{R}$)

## Analyzing a Categorical
- Analyzing a categorical variable $C$ is about computing how often it takes each possible label $\ell$: How are the data spread out across labels?

- A **sample proportion** is the fraction of observations taking the value $\ell$

- Proportions of labels, among non-missing values: 
    - `df[var].value_counts(normalize=True)`
- Proportions of labels, including missing values as an additional category: 
    - `df[var].value_counts(normalize=True, dropna=False)`

- Bar/count plot for visualization: 
    - `sns.countplot(x=df[var],stat='proportion')`
    - `sns.countplot(data=df, x=var, stat='proportion')`

## Analyzing a Numeric

- Analyzing a numeric variable $x$ is about computing how of: How are the data spread out across numeric values?
- To visualize the variable, `sns.histplot( df[var], bins=50)`
- For basic numeric summary, `df[var].describe()`

## Mean and Variance

- How disperse is your variable, $X = (x_1, ... , x_n)$?
- The **sample mean** is a standard measure of central tendency, the arithmetic average of the data:
$$
M(X) = \dfrac{x_1 + x_2 + ... + x_n}{n} = \frac{1}{n} \sum_{i=1}^n x_i
$$
- The **sample variance** is the arithmetic average of sum of squares of the observations from the mean,
$$
V(X) = \dfrac{1}{n} \sum_{i=1}^n (x_i - M(X))^2
$$
- The **sample standard deviation** is the square root of sample variance: $\text{sd}(x) = \sqrt{V(X)}$

a SD peanilizes things that are very far away much more, which we want to do sometimes

a robust statistic: things hat are very far away do not affect the statistic as much 
 a median is more robust than a mean: an outlier affects the median less than the mean 

Robust: a median, interquartile range 
an outlier will pull the mean and the deviation 

we want: balances, continuous and differentaible

## Median

- The mean and variance are particular sensitive to **outliers**: Values that are atypically high or low, and exert a lot of leverage on $M(X)$ and $V(X)$
- **Robust statistics** is the study of estimators that are less sensitive to outlier
- The **sample median** is a robust measure of central tendency, and corresponds to the value of $X$ for which half the data are above it, and half the data are below it:

$$\mathrm{med}(x) = \begin{cases}
x_{\left(\frac{n+1}{2}\right)} & n \text{ odd} \\[4pt]
\tfrac{1}{2}\left(x_{\left(\frac{n}{2}\right)} + x_{\left(\frac{n}{2}+1\right)}\right) & n \text{ even}
\end{cases}$$

- `df['var'].med()`

Interquartile Range:

25%-75% of the data

In [27]:
q1 = df['Number Of Reviews'].quantile(0.25)
q3 = df['Number Of Reviews'].quantile(0.75)

print(q1)
print(q3)

0.0
13.0

## Quantiles

- The median targets "this is the value for which half of the sample is below, and half of the sample is above"
- What if said, "I want to find the value for which a proportion $f$ of the sample is below, and $(1-f)%$ of the sample is above"
- This is called the **$f$-th quantile**:
  
$$x_{(1)} \le x_{(2)} \le \cdots \le x_{(n)}, \qquad \hat q_f = x_{(\lceil n f \rceil)}$$

- `np.quantile(X,f)`

In [ ]:
from math import ceil
#70th percentile

def quantile(X, frac):
    values = sorted(x)


#DNF

## Two Useful Transformations
- Almost every dataset I have ever opened has a few data with **long tails**: The mean is much larger or smaller than the median, because the data have a very small number of very large values
- To visualize and numerically stabilize these kinds of variables, we often take the **natural logarithm**, `df['var_ln'] = np.log(df[var])`
    - The natural log has two problems: At zero it goes to $-\infty$ and it is not defined for negative numbers
- The better choice is called the **inverse hyperbolic sine** or **arcinsh**, `df['var_ihs'] = np.arcsinh(df[var])`:
$$
i(x) = \ln \left( x + \sqrt{x^2+1} \right) 
$$
- This is defined for positive and negative values and takes the value zero at zero

# 2. Pairs of Variables

## Pairs of Categoricals

- To break out counts by two categoricals at the same time, we use a **contingency table** or **cross-tabulation**: `pd.crosstab(df[var1], df[var2])`
- This provides the joint counts for two categorical variables, allowing us to see how they vary together or not

In [29]:
pd.crosstab(df["Beds"], df["Property Type"])

Property Type,Apartment,Bed & Breakfast,Boat,Bungalow,Cabin,Camper/RV,Castle,Chalet,Condominium,Dorm,House,Hut,Lighthouse,Loft,Other,Tent,Townhouse,Treehouse,Villa
Beds,,,,,,,,,,,,,,,,,,,
0.0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1.0,18415,126,2,2,1,3,1,1,53,18,1149,1,0,460,36,4,66,1,3
2.0,5906,38,5,1,0,0,0,0,25,7,423,1,1,159,8,0,32,1,2
3.0,1753,4,0,1,1,1,0,0,8,4,208,0,0,71,2,0,15,2,1
4.0,596,7,1,0,0,2,0,0,3,0,122,0,0,39,0,0,12,0,1
5.0,186,1,0,0,0,0,0,0,2,0,77,0,0,14,0,0,4,0,0
6.0,105,2,0,0,0,0,0,0,2,1,53,0,0,8,1,0,4,0,1
7.0,33,0,0,0,0,1,0,0,1,0,9,0,0,0,0,0,1,0,0
8.0,10,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0
9.0,7,1,0,0,0,0,0,0,0,0,4,0,0,1,0,0,2,0,0
10.0,6,1,0,0,0,0,0,0,0,0,8,0,0,1,0,0,0,0,0
11.0,2,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0
12.0,2,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0
16.0,2,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0

## Pairs of Numerics

- How do we visualize the relationship between two variables?
- The numeric version of a contingency table is a scatterplot: `sns.scatterplot( x = df[var1], y=df[var2], alpha = .15 )`
- We often want to summarize that picture with a number, and typically use
$$
\text{cov}(X,Y) = \frac{\sum_{i=1}^n (x_i - M(X))(y_i - M(Y))}{n}
$$

- This can easily be computed: `df[[var1, var2]].cov()`

In [34]:
# df.groupby("Property Type")["Price"].mean()

#not all of the functions can take the mean function for : df.groupby("Property Type").mean()

# so we add ["Price"]

# now it takes the mean of the price grouped by the proprty type 

df.groupby("Property Type")["Price"].mean().sort_values()

Property Type
Lighthouse          39.000000
Hut                 75.000000
Dorm                76.354839
Chalet              99.000000
Camper/RV          103.571429
Bed & Breakfast    106.572222
Tent               126.250000
Treehouse          149.500000
Castle             150.000000
Bungalow           150.750000
Boat               153.625000
House              156.722967
Apartment          162.045642
Cabin              165.000000
Townhouse          203.933824
Loft               221.960159
Condominium        256.585106
Villa              328.000000
Other              394.659574
Name: Price, dtype: float64

## Numeric by Categorical

- To **conditional** analysis of a numeric variable `num` on a categorical variable `cat`, we perform an analysis on subgroups of the data determined by their labelling
- To visualize a numeric conditional on a categorical, you can use `hue`: `sns.kdeplot( x = df[num], hue = df[cat], fill=True)`

## Group By
- A general description by groups: 
    - `df[[cat,num]].groupby(cat).describe()`
- Specific statistics: `df[[cat,num]].groupby(cat).count()` or `.mean()`, `.sum()`, `.count()`, etc.
- For a custom function, `fcn()`: `df[[cat,num]].groupby(cat).agg(fcn)`
- If you are analyzing the top or bottom of a set of observations, it often makes sense to use `.sort()` at the end